version: "3.6"

services:
  paper-service:
    image: paper-service:dev
    tty: true
    container_name: paper-service-test
    command: sh -c "yarn && yarn test:coverage"
    build:
      context: .
      dockerfile: ./docker/development.Dockerfile
    volumes:
      - ./coverage:/usr/app/coverage
      - ./package.json:/usr/app/package.json
      - ./jest:/usr/app/jest
      - ./yarn.lock:/usr/app/yarn.lock
      - ./tsconfig.json:/usr/app/tsconfig.json
      - ./jest.config.js:/usr/app/jest.config.js
      - ./.eslintrc.json:/usr/app/.eslintrc.json
      - ./.eslintignore:/usr/app/.eslintignore
      - ./src:/usr/app/src
    networks:
      - tcdl-paper-service-test

  paper-service-db:
    container_name: paper-service-db-test
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tcdl-test
    networks:
      - tcdl-paper-service-test
   
  # Uncomment for init pgadmin ui instance
  # paper-pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user@domain.com
  #     PGADMIN_DEFAULT_PASSWORD: SuperSecret
  #   ports:
  #     - 5050:80
  #   networks:
  #     - tcdl-paper-service

networks:
  tcdl-paper-service-test:
    driver: bridge