name: paper-service-development
on: 
  pull_request:
    branches:
      - 'development'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.test.yml build
      - name: Test
        run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ./coverage/lcov.info:lcov